apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: cartography-k8s  
  namespace: appsec
  labels:
    team: appsec
    apiserver-access: enabled
spec:
  schedule: "{{schedule}}"
  concurrencyPolicy: Forbid
  image: "{{image}}"
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  command:
    - cartography
    - --neo4j-uri
    - bolt://neo4j-bolt.appsec.${{hostname}}
    - --neo4j-user
    - neo4j
    - --neo4j-password-env-var
    - NEO4J_PASSWORD
    - --selected-modules
    - create-indexes,kubernetes
    - --k8s-kubeconfig
    - /var/run/configmaps/cartography-k8s-kubeconfig/kubeconfig
  envFrom:
    - secret: neo4j
  env:
    - name: OTEL_LOGS_EXPORTER
      value: otlp
  filesFrom:
    - configmap: cartography-k8s-kubeconfig
  accessPolicy:
    outbound:
      rules:
        - application: {{neo4jApp}}
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2048Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: python
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cartography-k8s-kubeconfig
  namespace: appsec
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: {{cluster}}
        cluster:
          server: https://kubernetes.default.svc
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    contexts:
      - name: {{cluster}}
        context:
          cluster: {{cluster}}
          user: cartography-k8s
    current-context: {{cluster}}
    users:
      - name: cartography-k8s
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
