apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: cartography-k8s  
  namespace: appsec
  labels:
    team: appsec
    apiserver-access: enabled
spec:
  image: "{{image}}"
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  command:
    - cartography
    - --neo4j-uri
    - bolt://neo4j-bolt.appsec.svc.cluster.local
    - --neo4j-user
    - neo4j
    - --neo4j-password-env-var
    - NEO4J_PASSWORD
    - --selected-modules
    - kubernetes
  envFrom:
    - secret: cartography-nais
  accessPolicy:
    outbound:
      rules:
        - application: neo4j
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1024Mi
