apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: cartography-github-manifests
  namespace: appsec
  labels:
    team: appsec
spec:
  schedule: "0 1 * * 6"
  concurrencyPolicy: Forbid
  image: "{{image}}"
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  command:
    - cartography
    - --neo4j-uri
    - bolt://neo4j-bolt.appsec.svc.cluster.local
    - --neo4j-user
    - neo4j
    - --neo4j-password-env-var
    - NEO4J_PASSWORD
    - --selected-modules
    - create-indexes,github
    - --github-config-env-var
    - GITHUB_CONFIG
    - --github-skip-archived-repo-manifests
    - --github-parallel-workers
    - "5"
    - --github-requested-syncs
    - "users,repos,personal_access_tokens,dependabot_alerts,teams,actions,commits,packages,supply_chain"
  envFrom:
    - secret: cartography
  env:
    - name: OTEL_LOGS_EXPORTER
      value: otlp
  accessPolicy:
    outbound:
      rules:
        - application: neo4j
      external:
        - host: github.com
        - host: api.github.com
  observability:
    autoInstrumentation:
      enabled: true
      runtime: python
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 3072Mi
