apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: appsec
  labels:
    team: appsec
spec:
  image: "{{image}}"
  port: 7474
  replicas:
    min: 1
    max: 1
  strategy:
    type: Recreate
  envFrom:
    - secret: cartography
  env:
    - name: NEO4J_server_memory_heap_initial__size
      value: "1G"
    - name: NEO4J_server_memory_heap_max__size
      value: "2G"
    - name: NEO4J_server_memory_pagecache__size
      value: "512m"
    - name: NEO4J_dbms_usage__report_enabled
      value: "false"
    - name: NEO4J_server_default__listen__address
      value: "0.0.0.0"
    - name: NEO4J_server_http_listen__address
      value: "0.0.0.0"
    - name: NEO4J_server_config_strict__validation_enabled
      value: "false"
    - name: NEO4J_server_directories_logs
      value: "/tmp/logs"
    - name: NEO4J_server_directories_run
      value: "/tmp/run"
  filesFrom:
    - persistentVolumeClaim: neo4j-data
      mountPath: /data
    - emptyDir: {}
      mountPath: /var/lib/neo4j/conf
    - emptyDir: {}
      mountPath: /var/lib/neo4j/run
    - emptyDir: {}
      mountPath: /logs
    - emptyDir: {}
      mountPath: /var/lib/neo4j/metrics
  accessPolicy:
    inbound:
      rules:
        - application: cartography
  liveness:
    path: /
    port: 7474
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /
    port: 7474
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 5
  resources:
    requests:
      memory: 4Gi
      cpu: 200m
    limits:
      memory: 6Gi
