name: Build & deploy Neo4j
on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@0e73849f69ff260ee27597553c0a7848ca4e9795
        id: docker-push-neo4j
        with:
          team: appsec
          dockerfile: Dockerfile.neo4j
          image_suffix: neo4j
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/neo4j.yaml
          IMAGE: ${{ steps.docker-push-neo4j.outputs.image }}
