name: Deploy Neo4j
on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@cd5ec5663feb0e05c3fa374d1fb442605b046c6b
        id: docker-push-neo4j
        with:
          team: appsec
          dockerfile: Dockerfile.neo4j
          image_suffix: neo4j
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/neo4j.yaml,.nais/neo4j-bolt.yaml
          IMAGE: ${{ steps.docker-push-neo4j.outputs.image }}
