name: Deploy cartography (K8s)
on:
  workflow_dispatch:
   inputs:
     image:
       type: string
       required: true
       description: 'Image to deploy'

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster: [dev-fss, dev-gcp, prod-fss, prod-gcp]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@fceb26518aacf0ca378decec413782d1c5926e1a # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/cartography-k8s.yaml
          IMAGE: ${{ inputs.image }}
          VAR: cluster=${{ matrix.cluster }}
